name: data
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - altair=4.0.1
  - argon2-cffi=20.1.0
  - attrs=19.3.0
  - automat=20.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bcrypt=3.2.0
  - beautifulsoup4=4.8.2
  - bleach=3.1.5
  - bokeh=1.4.0
  - boto=2.49.0
  - boto3=1.13.19
  - botocore=1.16.19
  - brotlipy=0.7.0
  - ca-certificates=2020.6.20
  - catalogue=1.0.0
  - certifi=2020.6.20
  - cffi=1.14.1
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - constantly=15.1.0
  - cookies=2.2.1
  - cryptography=3.1
  - cssselect=1.1.0
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - cymem=2.0.3
  - cython-blis=0.4.1
  - cytoolz=0.10.1
  - dask=2.11.0
  - dask-core=2.11.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - dill=0.3.1.1
  - distributed=2.25.0
  - docutils=0.15.2
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.9
  - flask=1.1.1
  - fontconfig=2.13.1
  - freetype=2.10.2
  - fsspec=0.8.0
  - gettext=0.19.8.1
  - glib=2.65.0
  - gmp=6.2.0
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5py=2.10.0
  - hdf5=1.10.6
  - heapdict=1.0.1
  - hyperlink=20.0.1
  - icu=64.2
  - idna=2.10
  - imageio=2.9.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - incremental=17.5.0
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - itsdangerous=1.1.0
  - jdcal=1.4.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.16.0
  - jpeg=9d
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab=1.2.6
  - jupyterlab_server=1.2.0
  - kiwisolver=1.2.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=10.0.1
  - locket=0.2.0
  - lxml=4.5.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.2
  - more-itertools=8.5.0
  - msgpack-python=1.0.0
  - murmurhash=1.0.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - networkx=2.4
  - ninja=1.10.1
  - nltk=3.4.5
  - notebook=6.1.3
  - numpy=1.18.1
  - olefile=0.46
  - openpyxl=3.0.3
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.0.1
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parsel=1.6.0
  - parso=0.7.1
  - partd=1.1.0
  - patsy=0.5.1
  - pcre=8.44
  - pdfminer.six=20191020
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - plac=0.9.6
  - pluggy=0.13.1
  - preshed=3.0.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - prompt_toolkit=3.0.7
  - psutil=5.7.2
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.9.0
  - py4j=0.10.7
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pycryptodome=3.9.7
  - pydispatcher=2.0.5
  - pygments=2.6.1
  - pyhamcrest=2.0.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pyspark=2.4.5
  - pytest=5.3.5
  - python=3.7.5
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.4.0
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.2
  - pyzmq=19.0.2
  - qt=5.9.7
  - qtconsole=4.7.6
  - qtpy=1.9.0
  - queuelib=1.5.0
  - readline=7.0
  - requests=2.23.0
  - responses=0.10.11
  - retrying=1.3.3
  - rise=5.6.1
  - s3transfer=0.3.3
  - scikit-image=0.16.2
  - scikit-learn=0.23.2
  - scipy=1.4.1
  - scrapy=1.8.0
  - seaborn=0.10.0
  - send2trash=1.5.0
  - service_identity=18.1.0
  - setuptools=49.6.0
  - simplejson=3.17.0
  - sip=4.19.8
  - six=1.15.0
  - sortedcontainers=2.2.2
  - soupsieve=2.0.1
  - spacy=2.2.3
  - sqlite=3.33.0
  - srsly=1.0.2
  - statsmodels=0.11.1
  - tblib=1.6.0
  - terminado=0.8.3
  - testpath=0.4.4
  - thinc=7.3.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toolz=0.10.0
  - torchvision=0.5.0
  - tornado=6.0.3
  - tqdm=4.43.0
  - traitlets=4.3.3
  - twisted=20.3.0
  - ujson=1.35
  - urllib3=1.25.10
  - vega=2.6.0
  - vega_datasets=0.8.0
  - w3lib=1.22.0
  - wasabi=0.7.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - xlrd=1.2.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zict=2.0.0
  - zipp=3.1.0
  - zlib=1.2.11
  - zope.interface=5.1.0
  - zstd=1.4.5
  - pip:
    - absl-py==0.10.0
    - alembic==1.4.2
    - appdirs==1.4.4
    - astunparse==1.6.3
    - async-generator==1.10
    - audioread==2.1.8
    - awscli==1.18.69
    - bash-kernel==0.7.2
    - branca==0.4.1
    - cachetools==4.1.1
    - certipy==0.1.3
    - colorama==0.4.3
    - cython==0.29.17
    - ediblepickle==1.1.3
    - expectexception==0.1.1
    - folium==0.10.1
    - gast==0.3.3
    - gensim==3.8.1
    - gitdb==4.0.5
    - gitpython==3.1.0
    - google-auth==1.21.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.31.0
    - ihtml==0.1.2
    - imbalanced-learn==0.6.2
    - inflection==0.5.1
    - ipython-sql==0.3.9
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyter-telemetry==0.1.0
    - jupyterhub==1.1.0
    - keras-preprocessing==1.1.2
    - lazy==1.4
    - librosa==0.8.0
    - llvmlite==0.34.0
    - mako==1.1.3
    - markdown==3.2.2
    - mrjob==0.7.1
    - mwparserfromhell==0.5.4
    - git+git://github.com/jupyterhub/nbserverproxy.git@v0.8.3  # JupyterHub proxy
    - nose==1.3.7
    - numba==0.51.1
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pamela==1.0.0
    - pmdarima==1.6.1
    - pooch==1.1.1
    - praw==6.5.1
    - prawcore==1.5.0
    - prettytable==0.7.2
    - protobuf==3.13.0
    - pytest-parallel==0.0.10
    - python-editor==1.0.4
    - graphviz==0.13.2
    - python-json-logger==0.1.11
    - pytidylib==0.3.2
    - quandl==3.5.0
    - requests-futures==1.0.0
    - requests-oauthlib==1.3.0
    - resampy==0.2.2
    - rsa==3.4.2
    - ruamel-yaml==0.16.10
    - ruamel-yaml-clib==0.2.0
    - scikit-surprise==1.1.0
    - smart-open==2.1.1
    - smmap==3.0.4
    - soundfile==0.10.3.post1
    - sqlalchemy==1.3.13
    - sqlparse==0.3.1
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==2.0
    - tensorflow==2.3.0
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - update-checker==0.18.0
    - websocket-client==0.57.0
    - wordcloud==1.6.0
    - wrapt==1.12.1

